### ISSUE TITLE
LazyLoadList

### ISSUE THREAD

**Issue by tplusrex** [CondeNast/react-slick#12]
## Cause

When lazy loading galleries the active slide is the only slide that gets rendered. There's no setting to allow slides to preload in advance.

## Effect

The slide div will render when active. In some cases we do not want to wait for the slide to render when active. We want the slide to initially render so by the time that slide is reached no additional render is needed. This makes for a smoother experience if something takes longer to load.

## Proposed Solution

Create a new slick setting property that accepts an array of slide numbers. Load those initial slides and render the other slides normally when lazy load is active.

**Comment by tplusrex** [comment]
Proposed Solution: https://github.com/CondeNast/react-slick/pull/11

**Comment by brokentone** [comment]
> When lazy loading galleries the active slide is the only slide that gets rendered. There's no setting to allow slides to preload in advance.

This is not my understanding of the situation. We have a setting of `lazyLoadOffset` which does allow you to set a range around the active slide to preload. https://github.com/CondeNast/react-slick#added-features

Is this not working for you?

**Comment by tplusrex** [comment]
The statement I made is false. Slides are preloading according to the `lazyLoadOffset`.

The difference between current implementation and proposed enhancement is being able to load select slides on initial render instead of loading slides as you move through the gallery. I'm hoping with this feature we can have more control over what slides we lazy load. Would be possible to load the first 5, 10, etc...to the right without loading the same amount of slides to the left.

**Comment by gkilian** [comment]
Closing as this is not a feature we want to introduce into the OOS projects
